### PR TITLE
CI: add build/lint/test workflow

### PR DESCRIPTION
**Pull request by Evalir**
Just something basic to get it going for now :).

### CODE REVIEW

**Review by prestwich — APPROVED** [review]

**Comment by prestwich** [comment]
Concept ACK

Checks fail because cargo.lock is not committed. Do you think we should commit it, or remove the  `--locked` argument from CI?

general rust recommendation is to not commit the .lock

**Comment by Evalir** [comment]
Ah yeah, this is my bad. Don't think we should commit the lockfile—will remove the `--locked` argument!

**Comment by Evalir** [comment]
ah yeah tests fail due to https://github.com/nomad-xyz/safe-sdk/pull/2#discussion_r1148634916 ; i think we should `#[ignore]` this test for now and just make sure we put this as an issue

**Comment by Evalir** [comment]
aight seems good to go—should we squash the pr?

**Comment by prestwich** [comment]
ya I'm one of those annoying "squash merge only" people :)

**Comment by Evalir** [comment]
oh ya no worries, me too 😛

**Pull request merged**
